name: Publish Extension

on:
  push:
    tags:
      - "v*" # Triggers on version tags like v1.0.0, v1.2.3, etc.

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install vsce (Visual Studio Code Extension CLI)
        run: npm install -g @vscode/vsce

      - name: Install ovsx (Open VSX Registry CLI)
        run: npm install -g ovsx

      - name: Install dependencies
        run: npm install

      - name: Update version in package.json
        run: |
          # Extract version from git tag (remove 'v' prefix)
          VERSION=${GITHUB_REF#refs/tags/v}
          # Update package.json version
          npm version $VERSION --no-git-tag-version

      - name: Package extension
        run: vsce package

      - name: Publish to Visual Studio Marketplace
        run: vsce publish -p ${{ secrets.VSCE_PAT }}

      - name: Publish to Open VSX Registry
        run: ovsx publish -p ${{ secrets.OVSX_PAT }}
